### ISSUE TITLE
Is there a way to do range based formatting?

### ISSUE THREAD

**Issue by vheon** [mhartington/formatter.nvim#45] opened 2021-05-22 14:30 UTC
I usually work on an old codebase where we don't want to format a whole file but rather only the new code that we touch. Is there a way to get the lines the operator was called with? or should I use the vim api to understand somehow how the formatter was called (like get the range from the `'<`/`'>` marks)?

**Comment by lukas-reineke** [comment] 2021-05-24 01:46
It's currently not supported, but would be a nice feature.
With #19 it wouldn't be that hard to implement either.

**Comment by mhartington** [comment] 2021-05-24 14:35
This is supported, just select the code you want to format and run `Format`. Unless there's something I'm missing, #19 is not really relevant in this case

**Comment by vheon** [comment] 2021-05-24 21:27
@mhartington ok but I guess what it does is grabbing the selection and send just that to the formatter which at least from my testing means that I'm losing the indentation of what I selected with respect to the rest of the code. It may be strictly related to my use case with clang-format for C++ where usually you send the whole file specifying the range you want to format so it knows how it should format your code based on what it has near it.

**Comment by lukas-reineke** [comment] 2021-05-25 02:29
> This is supported, just select the code you want to format and run `Format`.

You are right, I totally forgot that is supported :sweat_smile: 

> I'm losing the indentation of what I selected with respect to the rest of the code

Yes, we just take the output of whatever formatter you use. There is no language specific logic in formatter.nvim.

You can try to run `:h equalprg` over the same range afterwards.
A very simple implementation would just be

```
autocmd User FormatterPost normal gv=
```

Maybe we could actually add this as an option. Run equalprg over the range, if the range is not the whole buffer.

**Comment by resolritter** [comment] 2021-08-28 11:59
I'll try to explain the problem here with different wording for clarity's sake.

When you format a range, formatter.nvim does [util.getLines](https://github.com/mhartington/formatter.nvim/blob/9866548f1c543ba90d7bb8a62c4fa939a5dcba46/lua/formatter/format.lua#L39) for the range and gets its lines **including their indentation**. The problem is that some formatters such as clang-format will just trim the indentation for the output you pass. i.e. if you send

```
    if (true) { return true; }
```

clang-format will return:

```
if (true) { return true; }
```

There you are losing the range's indentation **due to the formatter**, not the plugin.

I can think of two ways of working around this:

1. If the formatter program supports it, specify the range through CLI arguments and send the whole file. That way the range's indentation will not be trimmed because the rest of the file is considered for context.

2. Have some option in formatter.nvim to manually insert the indentation from startLine to the formatter's output. It would be an option because some formatters might preserve the indentation, unlike clang-format.

Naively restoring the range with `gv` (suggested in https://github.com/mhartington/formatter.nvim/issues/45#issuecomment-847483345) would not work because the visual positions from **before** formatting could no longer make sense after the range is formatted; maybe it would work if you updated the visual marks' positions before triggering `FormatterPost`.

**Comment by Kypert** [comment] 2021-09-05 18:34
Inspired by @resolritter, I followed option 1 and came up with something that seems to work for me (https://github.com/Kypert/formatter.nvim/compare/master...fix/45). But since I am no pro when it comes to lua, there are probably better idioms to follow. Please let me know if you are interested in a PR @mhartington.

**Comment by lukas-reineke** [comment] 2021-09-06 02:22
always open a PR :+1:

a couple comments though
1. your code currently only covers non-stdin, for it to get merged it needs to support stdin as well.
2. the difficult part of doing this is running multiple formatter, and your code also doesn't solve that.
   If the first formatter changes the number of lines that were originally selected, the next formatter now formats a different selection.

**Comment by Kypert** [comment] 2021-09-11 11:59
Sorry, I was not aware of the use-case of chaining multiple formatters and I agree, that sounds tricky to solve - especially since I do not know how to even setup such scenario for testing locally in the first place :) If this is a hard requirement, then I am afraid my change will have to stay side-lined (although it covers my day-job needs).

**Comment by lukas-reineke** [comment] 2021-09-11 13:02
If you put two formatters in the list for the same filetype, it will chain the formatting.

```lua
require('formatter').setup({
  filetype = {
    javascript = {
      function()
        return {
          exe = "prettier",
          args = {"--stdin-filepath", vim.fn.fnameescape(vim.api.nvim_buf_get_name(0)), "--single-quote"},
          stdin = true
        }
      end,
      function()
        return {
          exe = "eslint",
          args = {"--stdin", "--stdin-filename", vim.fn.fnameescape(vim.api.nvim_buf_get_name(0)), "--fix-to-stdout"},
          stdin = true
        }
      end
    },
  }
})
```

It would be a pretty big breaking change to not support this anymore. And I also think it is a much more important feature than fixing the indentation after range formatting.

**Comment by GZLiew** [comment] 2021-11-20 09:59
did anyone came out a solution for this regarding the indentation not working after a partial formatting?

**Comment by LimbicSys** [comment] 2021-12-16 07:09
You can use `vim.lsp.buf.range_formatting()` alternatively.

**Comment by Hrle97** [comment] 2022-07-30 13:27
Closing this in favor of #176 since this would be solved if formatting was powered by treesitter.

**Closed by Hrle97** 2022-07-30 13:27 UTC
Labels: question
